services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bar-crawler-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://user:pass@mongodb:27017/crawlr?authSource=admin
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./build:/app/build
      - /app/node_modules
    restart: unless-stopped
    command: npm run main
    # depends_on:
    #   - db

  db:
    image: mongo:8.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    command: mongod --bind_ip_all

volumes:
  mongodb_data:
